// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNN4PEJLBjDkH-W5dva-ZHxeKLW8bUHzk',
    appId: '1:560648403823:web:09dd3dcef28ead0785869a',
    messagingSenderId: '560648403823',
    projectId: 'tool-pool',
    authDomain: 'tool-pool.firebaseapp.com',
    storageBucket: 'tool-pool.appspot.com',
    measurementId: 'G-XLZ3S3V36G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqIHGvkoCuDRfkvj62ygVIkWRosJfzr5w',
    appId: '1:560648403823:android:92759f424835a49e85869a',
    messagingSenderId: '560648403823',
    projectId: 'tool-pool',
    storageBucket: 'tool-pool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdY57IT0VhNkEi_Lr-pVEdAgUuIE8zVx4',
    appId: '1:560648403823:ios:4450a277be87e79b85869a',
    messagingSenderId: '560648403823',
    projectId: 'tool-pool',
    storageBucket: 'tool-pool.appspot.com',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdY57IT0VhNkEi_Lr-pVEdAgUuIE8zVx4',
    appId: '1:560648403823:ios:8dffb42a49fc25c585869a',
    messagingSenderId: '560648403823',
    projectId: 'tool-pool',
    storageBucket: 'tool-pool.appspot.com',
    iosBundleId: 'com.example.namerApp.RunnerTests',
  );
}
