// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ECMisdSqLb0y1eqLi-s8qDNBvtwV9Bk',
    appId: '1:259613853445:web:38d83f14a36ef3952f596c',
    messagingSenderId: '259613853445',
    projectId: 'essdev-tool-sharing-app',
    authDomain: 'essdev-tool-sharing-app.firebaseapp.com',
    storageBucket: 'essdev-tool-sharing-app.appspot.com',
    measurementId: 'G-DZF4E0341X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwy_n088rqAPbj5J8N3EuIspgrekiMQkc',
    appId: '1:259613853445:android:4651e990c5d0fbe32f596c',
    messagingSenderId: '259613853445',
    projectId: 'essdev-tool-sharing-app',
    storageBucket: 'essdev-tool-sharing-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9R4fZ7I5PtjYTv2wL8sFnSY7D6qcw3cs',
    appId: '1:259613853445:ios:c8a21c92ce2143642f596c',
    messagingSenderId: '259613853445',
    projectId: 'essdev-tool-sharing-app',
    storageBucket: 'essdev-tool-sharing-app.appspot.com',
    iosBundleId: 'com.example.namerApp',
  );
}
